baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'JcGgOs'
theme = 'temple'
copyright = "©2022 - 2025"

pygmentsStyle = "friendly"
pygmentsCodeFences = true
favicon_location = "favicon.ico" # This assumes it's in static/favicon.ico

[params]
  topmenu = "categories"

[taxonomies]
  tag = "tags"
  category = "categories"

[params.author]
  name = "JcGgOs"
  github = "JcGgOs"
  email = "287828521@qq.com"
  twitter = "bad_leek"

[caches]
  [caches.images]
    dir = ':cacheDir/images'